#!/bin/bash
# Helper script to generate and display migration token setup instructions

echo "=== Moments Production Migration Setup ==="
echo ""
echo "Step 1: Generate your secure migration token"
echo "Run this command and copy the output:"
echo ""
echo "  openssl rand -hex 32"
echo ""
echo "Example output:"
echo "  a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
echo ""
echo "---"
echo ""
echo "Step 2: Add to Vercel Environment Variables"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select 'moments' project"
echo "3. Click Settings → Environment Variables"
echo "4. Click 'Add Environment Variable'"
echo "5. Key: MIGRATION_TOKEN"
echo "6. Value: <paste your token from Step 1>"
echo "7. Environment: Production"
echo "8. Click Save"
echo ""
echo "---"
echo ""
echo "Step 3: Redeploy the project"
echo "1. Go to Deployments tab"
echo "2. Click ... on latest deployment"
echo "3. Click Redeploy"
echo "4. Wait for 'Ready' status"
echo ""
echo "---"
echo ""
echo "Step 4: Run migrations"
echo "Once redeployed, run:"
echo ""
echo "  curl -X POST 'https://moments-us-app.vercel.app/api/migrate?token=<YOUR_TOKEN>'"
echo ""
echo "Replace <YOUR_TOKEN> with the actual token from Step 1"
echo ""
echo "Expected response (201 or 200):"
echo '  {"status":"ok","message":"Migrations completed successfully","output":"..."}'
echo ""
echo "---"
echo ""
echo "Step 5: Test registration"
echo ""
echo "  curl -X POST 'https://moments-us-app.vercel.app/api/auth/register' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"name\":\"Test\",\"phone\":\"+1234567890\",\"timezone\":\"UTC\"}'"
echo ""
echo "Should return 201 with user data."
echo ""
